platform :ios, '9.0'

target 'semesterProjectGroup23' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for semesterProjectGroup23
pod 'Starscream', '~> 3.0.2'
pod 'CorePlot', '~> 2.2'

end
